---
baseURL: https://missing-dots.in
languageCode: en-us
title: Missing Dots
pygmentsstyle: monokai
theme: hugo-notepadium
style: "auto"
paginate: 6
social:
  twitter: "#"
  github: "#"
taxonomies:
  author: authors
permalinks:
  posts: ":title"
showCategories: true       
showTags: true            
