---
baseURL: https://missing-dots.in/
languageCode: en
title: Missing Dots
pygmentsstyle: monokai
theme: hugo-kiera
style: auto
paginate: 6
social:
  twitter: "#"
  github: "#"
taxonomies:
  author: authors
  category: categories
  tag: tags
  series: series
permalinks:
  post: ":sections/:title"
showCategories: true
showTags: true
DefaultContentLanguage: en
enableInlineShortcodes: true
footnoteReturnLinkContents: "^"
params:
  author: Sapna Rani Kulshreshtha
  pseudo: Sapna Rani
  tagline: A simple blog on history, food, culture, and some forgotten stories.
  indexHeadline: " "
  headline: " "
  menu: 
  main:
  - identifier: about
    name: About
    title: About
    url: "/about/"
    weight: 0
  - identifier: author
    name: Author
    title: Author
    url: "/author/"
    weight: 0
  - identifier: posts
    name: Posts
    title: Posts
    url: "/posts/"
    weight: 0
  - identifier: tags
    name: Tags
    title: Tags
    url: "/tags/"
    weight: 0
  - identifier: categories
    name: Categories
    title: Categories
    url: "/categories/"
    weight: 0
  - identifier: series
    name: Series
    title: Series
    url: "/series/"
    weight: 0
copyright: Copyright &copy; 2020 - Sapna Rani Kulshreshtha
canonifyurls: true
noLicense: true
